#!/bin/bash
# Kommentar
trap "exit" INT TERM ERR
trap "kill 0" EXIT
echo „Hallo $USER!“
python seriell-mqtt.py &
python mqtt-linear.py &
python mqtt-binary.py &
#gnome-shell -e echo "test"
echo "Fertig"
wait