#!/bin/bash
# Kommentar
trap "exit" INT TERM ERR
trap "kill 0" EXIT
echo „Hallo $USER!“
python seriell-mqtt.py &
python mqtt-linear.py &
python mqtt-lighthouse.py &
cd /home/pi/libsurvive/
./api_example &)
#gnome-shell -e echo "test"
echo "Fertig"
wait